export type Difficulty = 'Easy' | 'Normal' | 'Advanced'

export type Question = {
    prompt: string
    options: string[]
    answer: number
    explanation: string
    difficulty: Difficulty
}

export type Track = {
    id: number
    title: string
    short: string
    blurb: string
    questions: Question[]
}

const q = (prompt: string, options: string[], answer: number, explanation: string, difficulty: Difficulty = 'Normal'): Question => ({ prompt, options, answer, explanation, difficulty })

const levels: Difficulty[] = ['Easy', 'Normal', 'Advanced']

const scenarioFrames = [
    'A teammate brings this issue during stand-up.',
    'You are reviewing a pull request under time pressure.',
    'A production alert points to this behavior.',
    'A new engineer asks you to explain this decision.',
    'The team is choosing between two valid implementations.',
    'A regression test exposes this case.',
    'A stakeholder reports this symptom after release.',
    'You are designing the first version of this feature.',
    'A performance investigation produces this clue.',
    'An incident review finds this pattern.',
    'A migration changes the surrounding constraints.',
    'A customer workflow depends on this behavior.',
    'The codebase has grown and this trade-off now matters.',
    'You are debugging a failure that only appears at scale.',
    'A reviewer asks which option is safest.',
    'You must make the decision reversible.'
]

const baseTracks: Track[] = [
    { id: 1, title: 'CS Fundamentals', short: 'Fundamentals', blurb: 'Systems, networks, runtime, and data foundations.', questions: [
        q('A mobile app feels frozen while parsing a 20 MB response synchronously on the JS thread. Which diagnosis is strongest?', ['The network must be using UDP.', 'The event loop cannot process other work until the synchronous parse yields.', 'The heap is always full when JSON is parsed.', 'A Promise automatically moves parsing to another core.'], 1, 'Async syntax does not make CPU-heavy synchronous work parallel. Yield, move work off the hot thread, or reduce the payload.', 'Advanced'),
        q('Four worker threads update a shared counter and the final count is low. What is the likely cause?', ['A cache miss', 'A race condition around a read-modify-write operation', 'A compiler error', 'DNS expiry'], 1, 'Concurrent interleaving can cause lost updates. Protect the critical section or use an atomic operation.'),
        q('A server accepts a request, but the caller cannot prove who sent it. Which concept is missing?', ['Authorization', 'Authentication', 'Horizontal scaling', 'Serialization'], 1, 'Authentication answers who you are; authorization decides what an authenticated identity may do.', 'Easy'),
        q('A database scans ten million rows for a frequently queried email column. What is the most direct improvement?', ['Add a B-tree index, accepting write and storage cost.', 'Add more loading spinners.', 'Convert values to strings.', 'Use a larger HTTP timeout.'], 0, 'An index trades storage and write overhead for faster reads by avoiding a full table scan.', 'Easy')
    ]},
    { id: 2, title: 'DSA & Algorithms', short: 'DSA', blurb: 'Structures, complexity, and patterns behind fast solutions.', questions: [
        q('You need the shortest path in an unweighted social graph. Which approach is the best default?', ['DFS with recursion', 'BFS with a queue and visited set', 'Quick Sort', 'A hash table without edges'], 1, 'BFS explores by distance layers, so first arrival is a shortest unweighted path.', 'Easy'),
        q('A BST built from sorted values behaves like a chain. What is search complexity?', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 2, 'An unbalanced BST loses the halving property and can degrade to linked-list behavior.'),
        q('A leaderboard repeatedly needs the highest score while accepting new scores. Which structure fits?', ['A max-heap', 'A FIFO queue', 'A linked list with random access', 'A min-heap only'], 0, 'A max-heap gives O(1) peek and O(log n) insertion/removal of the maximum.', 'Easy'),
        q('A function recursively computes factorial(n) but returns only the number. Which complexity is accurate?', ['O(n!) because the result is large', 'O(n) because it makes n recursive calls', 'O(1) because it returns one value', 'O(2^n) because it is recursive'], 1, 'Do not confuse the size of a numeric result with the number of operations performed.', 'Advanced')
    ]},
    { id: 3, title: 'Clean Code & Design', short: 'Clean Code', blurb: 'Readable boundaries, refactoring, and maintainable decisions.', questions: [
        q('A 400-line function validates input, persists data, sends email, and formats a report. Best first refactor?', ['Add a longer comment.', 'Split cohesive responsibilities behind small interfaces.', 'Duplicate it for each caller.', 'Make every variable global.'], 1, 'Multiple reasons to change signal low cohesion and an SRP violation.', 'Easy'),
        q('A payment service constructs a concrete database client internally, so tests need a live database. Best improvement?', ['Dependency injection', 'Inheritance from the database', 'More comments', 'A global singleton'], 0, 'Inject the repository so tests can supply a fake and production can supply the real implementation.'),
        q('A subtype throws when callers use a valid base-class operation. Which principle is violated?', ['DRY', 'Liskov Substitution', 'YAGNI', 'KISS'], 1, 'Subtypes must preserve the behavioral contract expected of the base type.', 'Advanced'),
        q('You need to switch between walking, driving, and transit routes at runtime without changing the caller. Which pattern fits?', ['Strategy', 'Factory only', 'Adapter only', 'Singleton'], 0, 'Strategy encapsulates interchangeable algorithms behind a common contract.', 'Advanced')
    ]},
    { id: 4, title: 'Git', short: 'Git', blurb: 'History, collaboration, recovery, and safe change management.', questions: [
        q('You need to inspect remote commits before deciding whether to integrate them. Which command is safest?', ['git pull', 'git fetch', 'git reset --hard', 'git revert'], 1, 'fetch downloads remote history without merging it into your current branch.', 'Easy'),
        q('A bad commit is already on a shared production branch. Which undo preserves collaboration?', ['git reset --hard', 'git revert', 'Delete .git', 'Rebase everyone'], 1, 'Revert creates a new commit that reverses the old one without rewriting shared history.'),
        q('After a mistaken reset, the branch pointer no longer names your last work. Where should you look first?', ['git reflog', 'git status only', 'package-lock.json', 'git clean'], 0, 'Reflog records where HEAD has pointed and often recovers apparently lost commits.', 'Advanced'),
        q('You need one bug-fix commit from another branch, not all its work. Which operation fits?', ['git cherry-pick', 'git clone', 'git init', 'git stash pop'], 0, 'Cherry-pick applies one selected commit onto the current branch.', 'Easy')
    ]},
    { id: 5, title: 'TypeScript', short: 'TypeScript', blurb: 'Types, narrowing, generics, and trustworthy runtime boundaries.', questions: [
        q('An API returns JSON typed as User, but malformed data crashes at runtime. What was missing?', ['A type annotation', 'Runtime validation at the untrusted boundary', 'A readonly modifier', 'An enum'], 1, 'TypeScript types disappear at runtime. Validate external data before treating it as User.', 'Advanced'),
        q('A function receives string | number and calls .toUpperCase() immediately. What should happen first?', ['Narrow the union with a runtime check.', 'Cast with as and trust it.', 'Use any.', 'Delete the string case.'], 0, 'Narrowing connects runtime evidence to the type checker.', 'Normal'),
        q('A helper should accept any type and return that same type without losing information. Which feature fits?', ['Generics', 'any', 'void', 'never'], 0, 'A generic preserves the relationship between input and output types.', 'Easy'),
        q('A patch endpoint accepts any subset of a User object. Which utility type models it?', ['Partial<User>', 'Record<User>', 'Pick<User, never>', 'Readonly<User>'], 0, 'Partial makes each property optional, fitting a partial update payload.')
    ]},
    { id: 6, title: 'React Native', short: 'React Native', blurb: 'Component state, performance, mobile lifecycle, and resilience.', questions: [
        q('A screen stores items and filteredItems in state; they drift after search. Best fix?', ['Store filteredItems twice.', 'Derive filteredItems from items and query.', 'Use a global variable.', 'Force a full reload.'], 1, 'Derived state should be calculated from source state rather than duplicated.'),
        q('A FlatList scrolls poorly because every row creates heavy objects and functions. What should you investigate?', ['Unnecessary re-renders and unstable references.', 'DNS resolution.', 'Git branches.', 'Normalization only.'], 0, 'Profile row rendering, stabilize meaningful references, and keep row work small.', 'Advanced'),
        q('A sensitive token must survive app restarts. Where should it live?', ['Plain AsyncStorage only', 'Platform secure storage such as Keychain/Keystore', 'A navigation param', 'A screenshot'], 1, 'Secure storage is designed for credentials; ordinary key-value storage is not equivalent protection.', 'Easy'),
        q('A user opens a notification and should land on a specific order screen. Which capability matters?', ['Deep linking', 'Memoization', 'A heap', 'Git bisect'], 0, 'Deep links map an external action to a screen and state.', 'Easy')
    ]},
    { id: 7, title: 'General SWE', short: 'Engineering', blurb: 'Requirements, delivery, testing, observability, and reliability.', questions: [
        q('A ticket says “make checkout fast.” What should happen before implementation?', ['Define measurable acceptance criteria and constraints.', 'Choose a library immediately.', 'Rewrite the database.', 'Wait for production to clarify it.'], 0, 'Turn vague requirements into testable outcomes such as latency targets and failure behavior.', 'Easy'),
        q('A release passes unit tests but fails with the real API. Which layer was missing?', ['Integration coverage', 'A linter', 'A branch name', 'A type alias'], 0, 'Integration tests verify boundaries between components and external systems.'),
        q('A service stays available with reduced features when recommendations are down. What property is this?', ['Fault tolerance', 'Perfect consistency', 'Syntax safety', 'Fast-forward merge'], 0, 'Fault-tolerant systems degrade intentionally instead of failing completely.', 'Advanced'),
        q('An API needs a breaking response while old mobile clients remain active. Safest approach?', ['Version the contract or provide compatibility during migration.', 'Change it silently.', 'Delete the old endpoint.', 'Ask clients to infer fields.'], 0, 'Versioning and compatibility protect consumers while adoption happens deliberately.', 'Easy')
    ]},
    { id: 8, title: 'Problem Solving', short: 'Reasoning', blurb: 'Constraints, patterns, estimation, and decisions under time.', questions: [
        q('A prompt asks for a schedule where tasks have prerequisites. What should you extract first?', ['Dependency constraints and what must precede what.', 'The fanciest algorithm name.', 'Answer choices only.', 'The UI layout.'], 0, 'Constraint extraction prevents solving a different problem.', 'Easy'),
        q('Your estimate is around 50, but exact calculation returns 50,000. What should you do?', ['Recheck units, assumptions, and arithmetic.', 'Round it up again.', 'Ignore the estimate.', 'Pick the largest option.'], 0, 'Estimation catches order-of-magnitude mistakes.'),
        q('Two solutions are correct: one is O(n) with extra memory, another O(n²) in place. What should decide?', ['Actual constraints and time/space trade-offs.', 'In-place is always better.', 'Which has more code.', 'Which uses recursion.'], 0, 'There is no best algorithm independent of constraints.', 'Normal'),
        q('A substring problem asks for the longest range satisfying a changing constraint. Which pattern should you consider?', ['Sliding window with expand/shrink rules.', 'Merge commit.', 'Binary tree rotation.', 'Exception swallowing.'], 0, 'A moving window avoids recomputing every range and often achieves linear time.', 'Advanced')
    ]},
    { id: 9, title: 'Communication', short: 'Communication', blurb: 'Clear, calm, direct communication in realistic team moments.', questions: [
        q('A manager says, “Could we maybe revisit this timeline?” Best interpretation?', ['It may be a softened request to discuss or change it; clarify the desired action.', 'Definitely approval.', 'Definitely rejection.', 'Unrelated to delivery.'], 0, 'Hedged language can soften a request. Confirm intent instead of assuming.', 'Advanced'),
        q('Which production update is most actionable?', ['“Still looking.”', '“Checkout errors rose to 8% after release; rollback is in progress, Alex owns mitigation, next update in 15 minutes.”', '“The backend is weird.”', '“Someone broke it.”'], 1, 'State impact, evidence, owner, action, and next checkpoint without blame.', 'Easy'),
        q('A teammate proposes an approach you disagree with. Best response?', ['Acknowledge the goal, explain the trade-off with evidence, and propose a test or decision path.', 'Reject their competence.', 'Stay silent and complain later.', 'Escalate immediately.'], 0, 'Focus on the work and shared goal. Make disagreement useful and testable.'),
        q('A requirement is ambiguous and implementation has not started. Best next move?', ['Ask focused questions and restate acceptance criteria in your own words.', 'Guess and build the largest version.', 'Wait for someone else to notice.', 'Document only after shipping.'], 0, 'Clarification is cheaper before code exists and protects delivery and relationships.')
    ]}
]

const trackAdditions: Record<number, Question[]> = {
    1: [q('A service receives more work than one CPU can finish. Which change adds capacity by using more machines?', ['Horizontal scaling', 'Changing a variable name', 'A hash collision', 'A stack frame'], 0, 'Horizontal scaling adds instances; a load balancer distributes incoming work.'), q('A process keeps allocating unreachable objects. What symptom is most likely?', ['A memory leak or growing heap usage', 'A faster DNS lookup', 'A compile-time type error', 'A smaller binary'], 0, 'Unreleased allocations consume memory.'), q('A client should retry without creating a second charge. Which property matters?', ['Idempotency', 'Inheritance', 'Recursion', 'Serialization'], 0, 'Idempotent operations have the same intended result when safely repeated.'), q('A team needs a durable record after process restarts. Which storage is appropriate?', ['A persistent database or append-only log', 'A local variable', 'A CPU register', 'A temporary stack frame'], 0, 'Process memory is lost on restart; durable storage persists history.')],
    2: [q('You must find a value in an unsorted list and cannot preprocess it. Which approach is correct?', ['Linear search in O(n)', 'Binary search in O(log n)', 'Heapify in O(1)', 'Tree rotation in O(log log n)'], 0, 'Without ordering, you may need to inspect each element.'), q('Array.shift() is used for every dequeue. What hidden cost matters?', ['Elements may be re-indexed, making dequeue O(n)', 'Dequeue becomes O(log n)', 'The queue becomes LIFO', 'The array is automatically sorted'], 0, 'A head index or linked-list-backed queue avoids repeated shifting.'), q('A two-pointer solution moves inward once. What justifies O(n)?', ['Each pointer moves at most n times overall', 'There are always two nested loops', 'Pointers make every lookup O(1)', 'The input is automatically sorted'], 0, 'Total pointer movement is bounded.'), q('What prevents DFS from visiting a cyclic graph forever?', ['A visited set', 'A max-heap', 'A second root', 'Sorting every edge'], 0, 'Mark nodes visited and skip already-seen nodes.')],
    3: [q('A module exposes its database connection and callers modify it directly. What boundary is missing?', ['Encapsulation', 'Binary search', 'A queue', 'A deployment'], 0, 'Encapsulation protects internal state.'), q('A class changes for validation, email, and schema reasons. What does that signal?', ['Too many responsibilities', 'Perfect cohesion', 'A stable abstraction', 'A pure function'], 0, 'Independent reasons to change suggest decomposition.'), q('A new provider should fit an existing interface without changing callers. Which goal applies?', ['Open for extension and closed for modification', 'Global mutable state', 'A deeper inheritance tree', 'Duplicated conditionals'], 0, 'Add an implementation behind a stable contract.'), q('A test needs business rules without network or clock behavior. What design helps?', ['Inject the clock and network boundary', 'Construct them inside every method', 'Use global state', 'Catch every exception silently'], 0, 'Injected volatile dependencies make deterministic tests possible.')],
    4: [q('Which command shows unstaged changes compared with the index?', ['git diff', 'git push', 'git tag', 'git clone'], 0, 'git diff shows changes not staged.'), q('A branch has no divergence from main and can move its pointer forward. What merge is this?', ['Fast-forward merge', 'Conflict-only merge', 'Cherry-pick', 'Detached checkout'], 0, 'Git moves the branch pointer without a merge commit.'), q('Which tool binary-searches commit history for a regression?', ['git bisect', 'git stash', 'git init', 'git clean'], 0, 'bisect tests midpoint commits.'), q('Which command shows one commit plus metadata and patch?', ['git show <commit>', 'git status --remote', 'git branch --delete-all', 'git fetch --hard'], 0, 'git show presents a specific commit and diff.')],
    5: [q('What helps narrow success and error objects using a kind field?', ['A discriminated union', 'any everywhere', 'A readonly array only', 'An unchecked assertion'], 0, 'A literal discriminant lets each branch expose valid fields.'), q('Which type maps any string key to a numeric count?', ['Record<string, number>', 'never[]', 'Partial<never>', 'void'], 0, 'Record models a typed dictionary.'), q('A Promise<User> is passed where User is expected. What is wrong?', ['The code has a Promise<User>, not a User yet.', 'Promises are always strings.', 'await blocks the entire OS.', 'User is a primitive'], 0, 'Await or handle the promise before using its value.'), q('What risk remains when using as Admin on unchecked API data?', ['The assertion validates nothing at runtime.', 'The API becomes encrypted.', 'The value is cloned deeply.', 'The compiler adds a permission check'], 0, 'Assertions only tell the compiler to trust you.')],
    6: [q('A component subscribes in useEffect. What must cleanup return?', ['An unsubscribe cleanup', 'A new component tree', 'A database transaction', 'A navigation drawer'], 0, 'Remove listeners to avoid leaks and stale updates.'), q('An array index is used as a key and items are inserted at the front. What can happen?', ['React may associate state with the wrong item', 'The list becomes a heap', 'The API becomes idempotent', 'Permissions are lost'], 0, 'Stable identity keys preserve logical item identity.'), q('A form value is driven by React state. What is React?', ['The source of truth', 'Only a visual cache', 'The database server', 'A permission prompt'], 0, 'Controlled inputs keep the value in state.'), q('A screen refreshes when active again after navigation. Which lifecycle matters?', ['Focus and blur events', 'Git reflog', 'SQL HAVING', 'Heapify'], 0, 'Navigation focus differs from initial mount.')],
    7: [q('What makes “the system should be secure” testable?', ['Concrete acceptance criteria for auth, auditability, and threat constraints.', 'More adjectives.', 'Code review only.', 'Nothing written down'], 0, 'Specific criteria turn quality into an engineering contract.'), q('A pipeline tests but does not scan dependencies or secrets. What gap remains?', ['Security checks in CI/CD', 'A UI animation', 'A linked-list pointer', 'A CSS reset'], 0, 'CI can catch supply-chain and secret risks.'), q('A payment retry creates two charges. What resilience concern is exposed?', ['Retries need idempotency and bounded backoff', 'Retries should be infinite', 'Timeouts guarantee safety', 'Queues remove all duplicates'], 0, 'Retries can duplicate side effects.'), q('Logs exist but requests cannot be linked to a database spike. What should be added?', ['Correlation IDs and tracing context', 'Fewer timestamps', 'Global variables', 'A larger logo'], 0, 'Correlated telemetry connects service boundaries.')],
    8: [q('Input n is at most 20 and a proposed solution is O(2^n). What should you conclude?', ['It may be acceptable under the constraint; verify time and output size.', 'Exponential is always invalid.', 'The constraint is irrelevant.', 'Only space matters'], 0, 'Constraints determine whether a trade-off is practical.'), q('How do you remove duplicates while preserving first-seen order?', ['A Set plus a single pass', 'Sort then discard order', 'Nested scans only', 'A tree without traversal'], 0, 'Set membership is average O(1) and scan order remains.'), q('A solution fails on empty input. What should you inspect?', ['Base cases and boundaries', 'Variable naming', 'Deployment region', 'Font family'], 0, 'Boundary inputs expose assumptions.'), q('What reading habit distinguishes must from could?', ['Separate necessary claims from possible claims.', 'Choose the detailed option.', 'Assume universality.', 'Ignore qualifiers'], 0, 'Qualifiers change the logical burden.')],
    9: [q('A status says “we should be okay” without evidence. What improves it?', ['State facts, risk, owner, next action, and checkpoint.', 'Add jargon.', 'Avoid naming risk.', 'Wait until the end'], 0, 'Actionable updates distinguish evidence from confidence.'), q('A reviewer says “clean this up.” What should you ask for?', ['Specific behavior, concern, and acceptance criterion.', 'An apology.', 'A larger PR.', 'No clarification'], 0, 'Specific feedback is actionable.'), q('A stakeholder changes the goal mid-implementation. What first?', ['Restate goal, impact, priority, and acceptance criteria.', 'Ignore scope change.', 'Blame them.', 'Ship both silently'], 0, 'Shared understanding prevents hidden scope conflict.'), q('A teammate is quiet after a proposal. What supports active listening?', ['Ask what concerns they have and pause.', 'Assume agreement.', 'Speak faster.', 'End the meeting'], 0, 'Silence is ambiguous; invite the person in.')]
}

const expandedTracks: Track[] = baseTracks.map((track) => ({ ...track, questions: levels.flatMap((difficulty) => Array.from({ length: 20 }, (_, index) => { const sourcePool = [...track.questions, ...(trackAdditions[track.id] ?? [])]; const source = sourcePool[index % sourcePool.length]; return { ...source, difficulty, prompt: `${scenarioFrames[index]} ${source.prompt}` } })) }))

const cyberQuestions: Question[] = [
    q('A login endpoint responds differently when a username exists versus when it does not. What risk does this create?', ['User enumeration', 'SQL normalization', 'DNS poisoning', 'A race condition'], 0, 'Different responses reveal which accounts exist.', 'Easy'),
    q('A user-supplied string is concatenated directly into a SQL query. What is the primary fix?', ['Parameterized queries or a safe query builder', 'Base64 encoding the string', 'Adding a longer timeout', 'Disabling database indexes'], 0, 'Parameter binding separates data from SQL instructions.', 'Easy'),
    q('A browser executes attacker-controlled script stored in a comment field for every viewer. Which vulnerability is this?', ['Stored cross-site scripting', 'CSRF only', 'Broken access control', 'Insecure deserialization'], 0, 'Stored XSS persists a payload and executes it in other browsers.', 'Easy'),
    q('A state-changing request accepts an existing cookie but has no anti-forgery protection. What attack should concern you?', ['Cross-site request forgery', 'Credential stuffing', 'Port scanning', 'Heap spraying'], 0, 'CSRF tricks an authenticated browser into an unwanted state change.', 'Normal'),
    q('An API checks a token but never checks whether the caller owns the account ID. What is missing?', ['Object-level authorization', 'TLS termination', 'Compression', 'Input encoding'], 0, 'Authentication alone is not permission.', 'Normal'),
    q('A password database is stolen. Which storage approach limits offline guessing damage?', ['A slow, salted password hash such as Argon2 or bcrypt', 'Plain SHA-1 without salt', 'Encrypted passwords with one shared key', 'Base64 strings'], 0, 'Password hashes should be one-way, salted, and intentionally expensive.', 'Easy'),
    q('A public repository contains a production secret. What should happen first?', ['Revoke or rotate it and investigate exposure.', 'Rename the variable only.', 'Add it to a README.', 'Wait for release.'], 0, 'Assume a committed secret is compromised.', 'Advanced'),
    q('A service accepts a JWT and trusts the algorithm value in its header. What is dangerous?', ['The verifier may accept an unintended algorithm.', 'JWTs cannot expire.', 'TLS becomes unnecessary.', 'The token becomes a hash.'], 0, 'Algorithm and key handling must be configured server-side.', 'Advanced')
]

const cyberCommandQuestions: Question[] = [
    q('Which command discovers exposed TCP ports and service versions on an authorized staging host?', ['nmap -sV staging.example.com', 'grep -R password .', 'openssl enc -d file.txt', 'git reset --hard'], 0, 'nmap performs authorized network discovery.', 'Easy'),
    q('Which command queries DNS records for a suspicious domain?', ['dig suspicious.example', 'chmod 777 suspicious.example', 'npm install suspicious.example', 'kill -9 dns'], 0, 'dig queries DNS records.', 'Easy'),
    q('Which command quickly inspects HTTP response headers?', ['curl -i https://api.example/health', 'rm -rf /tmp/api', 'passwd --delete api', 'tar --extract api'], 0, 'curl -i displays response headers and body.', 'Easy'),
    q('Which command lists listening sockets and owning processes on Linux?', ['ss -tulpn', 'openssl rand -hex 4', 'git log --oneline', 'jq . users.json'], 0, 'ss -tulpn lists TCP/UDP listeners.', 'Normal'),
    q('Which command captures authorized packet evidence to a pcap file?', ['tcpdump -i eth0 -w capture.pcap', 'curl -X DELETE /var/log', 'nmap --delete-cache', 'sha256sum --repair'], 0, 'tcpdump captures packets for later analysis.', 'Normal'),
    q('Which command checks a server certificate and TLS handshake details?', ['openssl s_client -connect example.com:443 -servername example.com', 'grep -R cert /dev/null', 'chmod 000 certificate', 'kubectl delete secret tls'], 0, 'OpenSSL exposes certificate-chain details.', 'Advanced'),
    q('Which tool extracts fields reliably from JSON in a security pipeline?', ['jq', 'nmap', 'openssl passwd', 'ssh-keygen -R'], 0, 'jq filters and transforms JSON safely.', 'Easy'),
    q('Which command verifies the digest of an incident artifact?', ['sha256sum artifact.zip', 'curl -X PATCH artifact.zip', 'chmod +x artifact.zip', 'git merge artifact.zip'], 0, 'Compare the digest with a trusted reference.', 'Easy'),
    q('Which tool scans a container image for known CVEs?', ['trivy image app:latest', 'trivy login user-password', 'curl --upload-file secrets app:latest', 'git stash --security'], 0, 'Trivy scans images for known vulnerabilities.', 'Easy'),
    q('Which command retrieves Kubernetes pod definitions for securityContext review?', ['kubectl get pods -A -o yaml', 'kubectl expose secrets publicly', 'rm -rf ~/.kube', 'nmap the source repository'], 0, 'kubectl can retrieve workload definitions for review.', 'Advanced')
]

function makeCyberTrack(id: number, title: string, short: string, blurb: string, source: Question[]): Track {
    return { id, title, short, blurb, questions: levels.flatMap((difficulty) => Array.from({ length: 20 }, (_, index) => { const question = source[index % source.length]; return { ...question, difficulty, prompt: `${scenarioFrames[index % scenarioFrames.length]} ${question.prompt}` } })) }
}

const tracks: Track[] = [...expandedTracks, makeCyberTrack(10, 'Network & Infrastructure Security', 'Network Security', 'Network defense, host hardening, traffic analysis, and secure infrastructure.', [...cyberQuestions.slice(3), ...cyberCommandQuestions.slice(0, 6)]), makeCyberTrack(11, 'Application, Identity & Cloud Security', 'App / Identity', 'Secure APIs, identity, cloud boundaries, and secure development.', [...cyberQuestions, ...cyberCommandQuestions.slice(6)]), makeCyberTrack(12, 'Security Operations & Incident Response', 'SOC / Response', 'Detection, evidence, resilience, governance, and professional incident handling.', [...cyberQuestions.slice(4), ...cyberCommandQuestions])]

export { levels, tracks }